theme: jekyll-theme-leap-day
title: Jakob Spencer Koerper homepage
description: This is a collection of my Python projects
## About Me

I am looking for the opportunity to work in a fast-paced, challenging environment that allows me to further develop my data science knowledge and skills. The Walt Disney Company’s culture has given me the opportunity to take ownership and responsibility for projects which in turn allowed me to improve myself at a rapid rate. I want to leverage my data science knowledge to find innovative solutions and improvements to the company’s operations. 

I have significant skills and experience in Excel, VBA,  Python, R Studios, Spark, Tabula, and SQL. I am constantly adding new reporting and analysis tools to my skill set, and leveraging them to create pivot tables, regression lines, big data analysis, etc. I am also very experienced in creating visualizations and communicating them to a wide range of audiences.

